name: Run upload test

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Oxipng
        run: |
          RELEASE_INFO=$(curl -s "https://api.github.com/repos/oxipng/oxipng/releases/latest")
          OXIPNG_LATEST_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | contains("x86_64-unknown-linux-musl.tar.gz")) | .browser_download_url')
          
          if [ -z "$OXIPNG_LATEST_URL" ] || [ "$OXIPNG_LATEST_URL" = "null" ]; then
            echo "Failed to find latest Oxipng release URL"
            echo "Available assets:"
            echo "$RELEASE_INFO" | jq -r '.assets[].name'
            exit 1
          fi
          
          echo "Downloading Oxipng from $OXIPNG_LATEST_URL"
          curl -L -o oxipng.tar.gz "$OXIPNG_LATEST_URL"
          tar -xzf oxipng.tar.gz
          find . -name "oxipng" -type f -executable | head -1 | xargs -I {} sudo mv {} /usr/local/bin/
          sudo chmod +x /usr/local/bin/oxipng
          oxipng --version

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download test video (Big Buck Bunny)
        run: |
          curl -L -o big.buck.bunny.2008.m4v "https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_640x360.m4v"

      - name: Copy config template
        run: cp data/templates/config.py data/config.py

      - name: Insert API key into config.py
        run: |
          echo "Attempting to insert API key."
          echo "Length of MY_API_KEY: ${#MY_API_KEY}"
          if [ -z "${MY_API_KEY}" ]; then
            echo "Warning: MY_API_KEY is empty or not set."
          else
            echo "MY_API_KEY is set."
          fi
          sed -i "s|\${API_KEY}|${MY_API_KEY}|g" data/config.py
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}

      - name: Run upload.py with Big Buck Bunny and check for errors
        run: |
          set -e
          set -o pipefail
          OUTPUT_FILE="upload_output.txt"
          python upload.py big.buck.bunny.2008.m4v -ua -ns --debug 2>&1 | tee $OUTPUT_FILE

          echo "--- Full Upload Script Output ---"
          cat $OUTPUT_FILE
          echo "--- End of Output ---"

          ERROR_PATTERNS=(
            "Traceback (most recent call last):"
            "An unexpected error occurred:"
            "Connection refused"
            "\[Errno 111\] Connection refused"
            "Error: Unable to import config."
          )

          ERROR_FOUND=0
          for pattern in "${ERROR_PATTERNS[@]}"; do
            if grep -q "$pattern" $OUTPUT_FILE; then
              echo "::error::Detected error pattern: $pattern"
              ERROR_FOUND=1
            fi
          done

          if [ $ERROR_FOUND -eq 1 ]; then
            echo "Critical error patterns found. Failing step."
            exit 1
          else
            echo "No critical error patterns detected."
          fi

      - name: Download test video (Tears of Steel)
        run: |
          curl -L -o tears.of.steel.2012.mkv "https://media.xiph.org/tearsofsteel/tears_of_steel_1080p.webm"

      - name: Run upload.py with Tears of Steel and check for errors
        run: |
          set -e
          set -o pipefail
          OUTPUT_FILE="upload_output.txt"
          python upload.py tears.of.steel.2012.mkv -ua -ns -siu --tmdb movie/133701 --imdb tt2285752 --tvdb 37711 --debug 2>&1 | tee $OUTPUT_FILE

          echo "--- Full Upload Script Output ---"
          cat $OUTPUT_FILE
          echo "--- End of Output ---"

          ERROR_PATTERNS=(
            "Traceback (most recent call last):"
            "An unexpected error occurred:"
            "Connection refused"
            "\[Errno 111\] Connection refused"
            "Error: Unable to import config."
          )

          ERROR_FOUND=0
          for pattern in "${ERROR_PATTERNS[@]}"; do
            if grep -q "$pattern" $OUTPUT_FILE; then
              echo "::error::Detected error pattern: $pattern"
              ERROR_FOUND=1
            fi
          done

          if [ $ERROR_FOUND -eq 1 ]; then
            echo "Critical error patterns found. Failing step."
            exit 1
          else
            echo "No critical error patterns detected."
          fi

      - name: Update README badge for master branch
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
        run: |
          DATE_STR=$(date -u "+%Y-%m-%d %H:%M UTC")
          FIRST_LINE=$(head -1 README.md)
          
          DOCKER_BADGE=$(echo "$FIRST_LINE" | grep -o '\[\!\[Create and publish a Docker image\][^]]*\]([^)]*)' || echo "[![Create and publish a Docker image](https://github.com/Audionut/Upload-Assistant/actions/workflows/docker-image.yml/badge.svg?branch=master)](https://github.com/Audionut/Upload-Assistant/actions/workflows/docker-image.yml)")
          TAG_BADGE=$(echo "$FIRST_LINE" | grep -o '\[\!\[Test run ([^)]*[0-9][0-9]*\.[0-9][^)]*)\][^]]*\]([^)]*)' || echo "")
          MASTER_BADGE="[![Test run (Master Branch)](https://img.shields.io/github/actions/workflow/status/Audionut/Upload-Assistant/test-run.yaml?branch=master&label=Test%20run%20(Master%20Branch%20${DATE_STR// /%20}))](https://github.com/Audionut/Upload-Assistant/actions/workflows/test-run.yaml?query=branch%3Amaster)"
          
          if [ -n "$TAG_BADGE" ]; then
            NEW_FIRST_LINE="$DOCKER_BADGE $MASTER_BADGE $TAG_BADGE"
          else
            NEW_FIRST_LINE="$DOCKER_BADGE $MASTER_BADGE"
          fi

          echo "$NEW_FIRST_LINE" > README.md.new
          tail -n +2 README.md >> README.md.new
          mv README.md.new README.md

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update master branch badge with latest run date [skip ci]" || echo "No changes to commit"
          git push

      - name: Update README badge for latest tag
        if: github.event_name == 'release'
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          DATE_STR=$(date -u "+%Y-%m-%d %H:%M UTC")
          FIRST_LINE=$(head -1 README.md)
          
          DOCKER_BADGE=$(echo "$FIRST_LINE" | grep -o '\[\!\[Create and publish a Docker image\][^]]*\]([^)]*)' || echo "[![Create and publish a Docker image](https://github.com/Audionut/Upload-Assistant/actions/workflows/docker-image.yml/badge.svg?branch=master)](https://github.com/Audionut/Upload-Assistant/actions/workflows/docker-image.yml)")
          MASTER_BADGE=$(echo "$FIRST_LINE" | grep -o '\[\!\[Test run (Master Branch)\][^]]*\]([^)]*)' || echo "")
          TAG_BADGE="[![Test run (${TAG_NAME})](https://img.shields.io/github/actions/workflow/status/Audionut/Upload-Assistant/test-run.yaml?branch=${TAG_NAME}&label=Test%20run%20(${TAG_NAME}%20${DATE_STR// /%20}))](https://github.com/Audionut/Upload-Assistant/actions/workflows/test-run.yaml?query=branch%3A${TAG_NAME})"

          if [ -n "$MASTER_BADGE" ]; then
            NEW_FIRST_LINE="$DOCKER_BADGE $MASTER_BADGE $TAG_BADGE"
          else
            NEW_FIRST_LINE="$DOCKER_BADGE $TAG_BADGE"
          fi

          echo "$NEW_FIRST_LINE" > README.md.new
          tail -n +2 README.md >> README.md.new
          mv README.md.new README.md

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update badge for tag ${TAG_NAME} [skip ci]" || echo "No changes to commit"

          git fetch origin master:master
          git checkout master
          echo "$NEW_FIRST_LINE" > README.md.new
          tail -n +2 README.md >> README.md.new
          mv README.md.new README.md

          git add README.md
          git commit -m "Update badge for tag ${TAG_NAME} [skip ci]" || echo "No changes to commit"
          git push origin master

      - name: Cleanup config.py
        if: always()
        run: rm -f data/config.py
